/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giaodien;
import java.util.HashSet;
import javax.swing.JOptionPane;
import model.*;

/**
 *
 * @author w7
 */
public class MainFrm extends javax.swing.JFrame {

    QLSinhVienPanel  qlsinhvienPanel;
    QLDiemPanel      qldiemPanel;
    NguoiDung user;

    public void setUser(NguoiDung user) {
        this.user = user;
        lblUser.setText("Chào: "+user.getTenDangNhap()+" - Đăng nhập với vai trò: "+user.getVaiTro());
        if(user.getVaiTro().equalsIgnoreCase("canbodaotao")){
            itemQLDiem.setEnabled(false);
            btnqlDiem.setEnabled(false);
            itemQLSinhVien.setEnabled(true);
            btnQlsinhvien.setEnabled(true);
        }
        else if(user.getVaiTro().equalsIgnoreCase("giangvien")){
            itemQLSinhVien.setEnabled(false);
            btnQlsinhvien.setEnabled(false);
            itemQLDiem.setEnabled(true);
            btnqlDiem.setEnabled(true);
        }
    }
    /**
     * Creates new form MainFrm
     */
    public MainFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        btnQlsinhvien = new javax.swing.JButton();
        btnqlDiem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        tabMain = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemQLSinhVien = new javax.swing.JMenuItem();
        itemQLDiem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ứng dụng quản lý đào tạo");

        jToolBar1.setRollover(true);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Login-icon-32.png"))); // NOI18N
        jButton1.setText("Đăng xuất");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        btnQlsinhvien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnQlsinhvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/10207-man-student-light-skin-tone-icon-32.png"))); // NOI18N
        btnQlsinhvien.setText("Quản lý sinh viên");
        btnQlsinhvien.setFocusable(false);
        btnQlsinhvien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQlsinhvien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQlsinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQlsinhvienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQlsinhvien);

        btnqlDiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnqlDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gpa-icon-32.png"))); // NOI18N
        btnqlDiem.setText("Quản lý điểm");
        btnqlDiem.setFocusable(false);
        btnqlDiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnqlDiem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnqlDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqlDiemActionPerformed(evt);
            }
        });
        jToolBar1.add(btnqlDiem);

        lblUser.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(0, 51, 153));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setText("Thông tin đăng nhập");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(298, Short.MAX_VALUE)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        jToolBar1.add(jPanel1);

        jMenu1.setText("Hệ thống");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout-icon-16.png"))); // NOI18N
        jMenuItem1.setText("Đăng xuất");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Button-Close-icon-16.png"))); // NOI18N
        jMenuItem2.setText("Thoát");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        itemQLSinhVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemQLSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/10207-man-student-light-skin-tone-icon-16.png"))); // NOI18N
        itemQLSinhVien.setText("Quản lý sinh viên");
        jMenu2.add(itemQLSinhVien);

        itemQLDiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemQLDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gpa-icon-24.png"))); // NOI18N
        itemQLDiem.setText("Quản lý điểm");
        jMenu2.add(itemQLDiem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Trợ giúp");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-help-about-icon-16.png"))); // NOI18N
        jMenuItem5.setText("Hướng dẫn sử dụng");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Help-icon-16.png"))); // NOI18N
        jMenuItem6.setText("Giới thiệu");
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMain)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabMain, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQlsinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQlsinhvienActionPerformed
        // TODO add your handling code here:
         if(qlsinhvienPanel==null)
         {
             qlsinhvienPanel = new QLSinhVienPanel(); 
             //add vào JTabedPanel
             tabMain.addTab("Quản lý sinh viên", qlsinhvienPanel);
         }
         tabMain.setSelectedComponent(qlsinhvienPanel);
         
    }//GEN-LAST:event_btnQlsinhvienActionPerformed

    private void btnqlDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqlDiemActionPerformed
        // TODO add your handling code here:
        if(qldiemPanel==null)
        {
           qldiemPanel = new QLDiemPanel();
           //add vào JTabedPanel
           tabMain.addTab("Quản lý điểm", qldiemPanel);
        }
        
        tabMain.setSelectedComponent(qldiemPanel);
    }//GEN-LAST:event_btnqlDiemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:   
        user = null;
        qldiemPanel = null;
        qlsinhvienPanel =null;
        tabMain.removeAll();
        LoginDialog logindig = new LoginDialog(this, true);
        logindig.setLocationRelativeTo(this);
        logindig.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Bạn muốn thoát chương trình","Thông báo",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
               //tạo đối tượng cửa sổ chính
               MainFrm  frm = new MainFrm();
               frm.setVisible(true); //hiện thị cửa sồ chính
               //tạo cửa sổ đăng nhập
               LoginDialog loginDlg = new LoginDialog(frm, true);
               loginDlg.setLocationRelativeTo(frm);
               //hiển thị cửa sổ đăng nhập
               loginDlg.setVisible(true);             
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQlsinhvien;
    private javax.swing.JButton btnqlDiem;
    private javax.swing.JMenuItem itemQLDiem;
    private javax.swing.JMenuItem itemQLSinhVien;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTabbedPane tabMain;
    // End of variables declaration//GEN-END:variables
}
